# Generated by Django 5.1 on 2025-03-06 17:27

import car_profile.car_profile_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[car_profile.car_profile_validators.CarUsernameValidator, car_profile.car_profile_validators.CarUsernameContainsValidator, django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(help_text='Age requirement: 21 years and above.', validators=[django.core.validators.MinValueValidator(21)])),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('profile_picture', models.URLField(blank=True)),
            ],
        ),
    ]
